### ISSUE TITLE
Phylostratum of other organism

### ISSUE THREAD

**Issue by vinaybaranwal** [HajkD/myTAI#1]
First of all congratulations for a very vivid explanation of every single step. Now the problem. I am trying to generate phylostraum for Oryza sativa. I have modified the headers as suggested with following.
[Oryza sativa] | [Eukaryota; Virdiplantae; Streptophyta; Streptophytina; Embryophyta; Tracheophyta; Euphyllophyta; Spermatophyta; Magnoliophyta; Liliopsida, core Liliopsida; commelinids, Poales; Poaceae; Oryzae; Oryza].

But somehow the perl script does not assign these genes to any of the strata. Arabidopsis file works fine.

Could you please suggest something?

**Comment by vinaybaranwal** [comment]
I think there is a need to change in the main blast database file. Beacuse there I can see that many other organisms beside Arabisopsis is place in core eudicot which is a novel grouping. Am I right?

**Comment by HajkD** [comment]
Thank you very much for pointing this out to me! The author of this Perl Script is my colleague Alexander and I will get in touch with him to solve this issue.

I am happy to help you with this issue as soon as I have concrete answers.

Thanks for your patience!

Kind regards,
Hajk

**Comment by vinaybaranwal** [comment]
Thanks for your prompt reply. I shall wait for that upgraded perl script. :-)

**Comment by HajkD** [comment]
Hi,

My colleague Alexander now wrote a new version of the createPSmap.pl script to generate phylostratigraphic maps. You can find instructions here: https://github.com/AlexGa/Phylostratigraphy . I hope that this will help you to finally compute the maps of your interest.

Cheers,
Hajk
