### ISSUE TITLE
Retriving parent taxonomy for specific Taxonomy ID

### ISSUE THREAD

**Issue by abb44** [HajkD/myTAI#2]
Do you know if is possible for an specific TAX ID retrieve the corresponding parent?. It is clear how to retrieve for an specific parent all the children but not the way around.

**Comment by HajkD** [comment]
Hi @abb44 ,

does this help?

```r
taxize::gethierarchyupfromtsn(tsn = taxize::get_tsn(searchterm = "Arabidopsis thaliana",
                                                    searchtype = "scientific"))
```

Please let me know if it worked so that I can close this issue.

Cheers,
Hajk
